image:
# - Visual Studio 2019 - Can't get Windows build to work yet
- ubuntu2004

build: off

environment:
  auth_token:
    secure: b3cWFxhvVOhKJNSTbKjFwhUzimbeQMqjb/eUlJLGMdaeZrBaqPI0A8H/J8Mmrre2
  matrix:
    - nodejs_version: 12.22.6
      platform: x64
    - nodejs_version: 14.18.0
      platform: x64
    - nodejs_version: 16.10.0
      platform: x64

install:
  # - cmd: set OPENSSL_ROOT_DIR="C:\OpenSSL-v111-Win64\lib\"
  # - cmd: cd %APPVEYOR_BUILD_FOLDER% && git submodule update --init --recursive
  - sh: cd "$APPVEYOR_BUILD_FOLDER" && git submodule update --init --recursive
  - sh: sudo apt-get update && sudo apt-get install -y cmake gcc ninja-build libssl-dev python3-pytest python3-pytest-xdist unzip xsltproc doxygen graphviz libssl-dev gcc-10 g++-10
  - sh: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10
  - sh: nvm install "$nodejs_version" && nvm use "$nodejs_version"
  - npm ci --ignore-scripts
  - npm run build:package
  - npm run tag_upload_binary_release

artifacts:
  - path: build/stage/*/*
