name: Build and Publish Binaries

on:
  release:
    types: [published]

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          # Linux builds
          - os: ubuntu-latest
            arch: x64
            target: linux
            cross: false
          - os: ubuntu-latest
            arch: ia32
            target: linux
            cross: false
          - os: ubuntu-latest
            arch: arm64
            target: linux
            cross: false
          - os: ubuntu-latest
            arch: arm
            target: linux
            cross: false

          # Windows builds
          - os: windows-latest
            arch: x64
            target: win
            cross: false
          - os: windows-latest
            arch: ia32
            target: win
            cross: false
          - os: ubuntu-latest
            arch: arm64
            target: win
            cross: true

          # macOS builds
          - os: macos-latest
            arch: x64
            target: mac
            cross: false
          - os: macos-latest
            arch: arm64
            target: mac
            cross: false

    env:
      npm_config_arch: ${{ matrix.arch }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Xcode CLI tools and build tools (macOS)
        if: runner.os == 'macOS'
        run: |
          xcode-select --install || echo "Xcode tools already installed"
          brew update
          brew install ninja cmake

      - name: Install build tools (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build cmake

      - name: Install Zig for cross-compilation
        if: ${{ matrix.cross }}
        run: |
          curl -L -o zig.tar.xz https://ziglang.org/download/0.11.0/zig-linux-x86_64-0.11.0.tar.xz
          tar xf zig.tar.xz
          echo "$PWD/zig-linux-x86_64-0.11.0" >> $GITHUB_PATH

      - name: Install dependencies
        run: npm install

      - name: Build for ${{ matrix.os }} ${{ matrix.arch }}
        run: |
          if [[ "${{ matrix.cross }}" == "true" ]]; then
            npm_config_arch=arm64 CC="zig cc -target aarch64-windows" npm run build:package
          else
            npm run build:package
          fi

  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Publish to npm
        run: npm publish

